version: '3.2'

services:
  yam-database:
    image: yam-database:test
    build: yam-database
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - yam-database:/var/lib/postgresql/data
    deploy:
      restart_policy:
        condition: on-failure

  yam-eae:
    image: yam-eae:test
    build: yam-eae
    depends_on:
      - yam-database
    deploy:
      restart_policy:
        condition: on-failure

  yam-search:
    image: yam-search:test
    build: yam-search
    depends_on:
      - yam-database
    deploy:
      restart_policy:
        condition: on-failure

  webapp:
    image: yam-webapp:test
    build: yam-webapp
    # remember, remember: dependencies not used when deploying stacks (compose only)
    depends_on:
      - yam-database
      - yam-eae
    networks:
      - default
      - proxy
    deploy:
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        - "traefik.port=9001"
        - "traefik.docker.network=proxy"
        - "traefik.frontend.entryPoints=http,https"
        - "traefik.frontend.redirect.entryPoint=https"
        - "traefik.frontend.headers.SSLRedirect=true"

  # this is for the reverse tunneling feature
  ssh:
    image: yam-ssh:test
    build: yam-ssh
    ports:
      - "22"
    networks:
      - default
      - proxy
    deploy:
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        - "traefik.port=8090"
        - "traefik.docker.network=proxy"
        - "traefik.frontend.entryPoints=http,https"
        - "traefik.frontend.redirect.entryPoint=https"
        - "traefik.frontend.headers.SSLRedirect=true"

volumes:
  yam-database:
networks:
  proxy:
   external:
     name: proxy
